/// Generated by AssetsRefGenerator on 2020/05/12
class Res {
  static const String bottom = "images/bottom.png";
  static const String fblogo = "images/fblogo.png";
  static const String four = "images/four.png";
  static const String googlelogo = "images/googlelogo.png";
  static const String one = "images/one.png";
  static const String partylogo = "images/partylogo.png";
  static const String three = "images/three.png";
  static const String two = "images/two.png";
}
